version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "8602:8602"
    environment:
      - NODE_ENV=development
      - PORT=8602
      - DATABASE_URL=mysql://user:password@mysql:3306/user_service_dev
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - JWT_SECRET=user-service-jwt-secret
      - JWT_REFRESH_SECRET=user-service-refresh-secret
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - mediq-network
    healthcheck:
      test: ["CMD", "node", "dist/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=user_service_dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mediq-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mediq-network

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  mediq-network:
    driver: bridge
