apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8602"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8602
    targetPort: 8602
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: user-service
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-headless
  labels:
    app: user-service
    component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8602
    targetPort: 8602
    protocol: TCP
  selector:
    app: user-service
